#!/bin/sh
MEETV_LOCAL_LIB="https://nut-abctech:PraditR1qa2ws@github.com/startsiden/meetv-local-lib.git"
MEETV_COMMON="https://nut-abctech:PraditR1qa2ws@github.com/startsiden/meetv-common.git"
MEETV_ADMIN="https://nut-abctech:PraditR1qa2ws@github.com/startsiden/meetv-admin.git"
MEETV_BACKEND="https://nut-abctech:PraditR1qa2ws@github.com/startsiden/meetv-backend.git"
MEETV_WS="https://nut-abctech:PraditR1qa2ws@github.com/startsiden/meetv-ws.git"
MEETV_WS_CLIENT="https://nut-abctech:PraditR1qa2ws@github.com/startsiden/meetv-ws-client.git"
MEETV_WEBX="https://nut-abctech:PraditR1qa2ws@github.com/startsiden/meetv-webx.git"

echo "Meetv Repositories clone."
echo "####NOTE. Ensure you have the permission to access meetv private repo"
echo "####Start cloning meetv-local-lib"
git clone "$MEETV_LOCAL_LIB"
echo "####Finished cloning meetv-local-lib"
echo "####Start cloning meetv-common"
git clone "$MEETV_COMMON"
echo "####Finished cloning meetv-common"
echo "####Start cloning meetv-admin"
git clone "$MEETV_ADMIN"
echo "####Finished cloning meetv-admin"
echo "####Start cloning meetv-backend"
git clone "$MEETV_BACKEND"
echo "####Finished cloning meetv-backend"
echo "####Start cloning meetv-ws"
git clone "$MEETV_WS"
echo "####Finished cloning meetv-ws"
echo "####Start cloning meetv-ws-client"
git clone "$MEETV_WS_CLIENT"
echo "####Finished cloning meetv-ws-client"
echo "####Start cloning meetv-webx"
git clone "$MEETV_WEBX"
echo "####Finished cloning meetv-webx"

